/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard.index'
import { Route as DashboardAdministrationRouteImport } from './routes/_dashboard.administration'
import { Route as DashboardForbiddenRouteImport } from './routes/_dashboard.forbidden'
import { Route as DashboardInfrastructureRouteImport } from './routes/_dashboard.infrastructure'
import { Route as DashboardProjectsRouteImport } from './routes/_dashboard.projects'
import { Route as DashboardAdministrationIndexRouteImport } from './routes/_dashboard.administration.index'
import { Route as DashboardAdministrationAuditLogsRouteImport } from './routes/_dashboard.administration.audit-logs'
import { Route as DashboardAdministrationRolesRouteImport } from './routes/_dashboard.administration.roles'
import { Route as DashboardAdministrationUsersRouteImport } from './routes/_dashboard.administration.users'
import { Route as DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersRouteImport } from './routes/_dashboard.projects.$projectId.environments.$environmentId.containers'
import { Route as DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdRouteImport } from './routes/_dashboard.projects.$projectId.environments.$environmentId.containers.$containerId'
import { Route as DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdIndexRouteImport } from './routes/_dashboard.projects.$projectId.environments.$environmentId.containers.$containerId.index'
import { Route as DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdInspectRouteImport } from './routes/_dashboard.projects.$projectId.environments.$environmentId.containers.$containerId.inspect'
import { Route as DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdLogsRouteImport } from './routes/_dashboard.projects.$projectId.environments.$environmentId.containers.$containerId.logs'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdministrationRoute = DashboardAdministrationRouteImport.update({
  id: '/administration',
  path: '/administration',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardForbiddenRoute = DashboardForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInfrastructureRoute = DashboardInfrastructureRouteImport.update({
  id: '/infrastructure',
  path: '/infrastructure',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsRoute = DashboardProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdministrationIndexRoute =
  DashboardAdministrationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardAdministrationRoute,
  } as any)
const DashboardAdministrationAuditLogsRoute =
  DashboardAdministrationAuditLogsRouteImport.update({
    id: '/audit-logs',
    path: '/audit-logs',
    getParentRoute: () => DashboardAdministrationRoute,
  } as any)
const DashboardAdministrationRolesRoute =
  DashboardAdministrationRolesRouteImport.update({
    id: '/roles',
    path: '/roles',
    getParentRoute: () => DashboardAdministrationRoute,
  } as any)
const DashboardAdministrationUsersRoute =
  DashboardAdministrationUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => DashboardAdministrationRoute,
  } as any)
const DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersRoute =
  DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersRouteImport.update(
    {
      id: '/$projectId/environments/$environmentId/containers',
      path: '/$projectId/environments/$environmentId/containers',
      getParentRoute: () => DashboardProjectsRoute,
    } as any,
  )
const DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdRoute =
  DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdRouteImport.update(
    {
      id: '/$containerId',
      path: '/$containerId',
      getParentRoute: () =>
        DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersRoute,
    } as any,
  )
const DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdIndexRoute =
  DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdRoute,
    } as any,
  )
const DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdInspectRoute =
  DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdInspectRouteImport.update(
    {
      id: '/inspect',
      path: '/inspect',
      getParentRoute: () =>
        DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdRoute,
    } as any,
  )
const DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdLogsRoute =
  DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdLogsRouteImport.update(
    {
      id: '/logs',
      path: '/logs',
      getParentRoute: () =>
        DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/login': typeof AuthLoginRoute
  '/administration': typeof DashboardAdministrationRouteWithChildren
  '/forbidden': typeof DashboardForbiddenRoute
  '/infrastructure': typeof DashboardInfrastructureRoute
  '/projects': typeof DashboardProjectsRouteWithChildren
  '/administration/audit-logs': typeof DashboardAdministrationAuditLogsRoute
  '/administration/roles': typeof DashboardAdministrationRolesRoute
  '/administration/users': typeof DashboardAdministrationUsersRoute
  '/administration/': typeof DashboardAdministrationIndexRoute
  '/projects/$projectId/environments/$environmentId/containers': typeof DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersRouteWithChildren
  '/projects/$projectId/environments/$environmentId/containers/$containerId': typeof DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdRouteWithChildren
  '/projects/$projectId/environments/$environmentId/containers/$containerId/inspect': typeof DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdInspectRoute
  '/projects/$projectId/environments/$environmentId/containers/$containerId/logs': typeof DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdLogsRoute
  '/projects/$projectId/environments/$environmentId/containers/$containerId/': typeof DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof DashboardIndexRoute
  '/login': typeof AuthLoginRoute
  '/forbidden': typeof DashboardForbiddenRoute
  '/infrastructure': typeof DashboardInfrastructureRoute
  '/projects': typeof DashboardProjectsRouteWithChildren
  '/administration/audit-logs': typeof DashboardAdministrationAuditLogsRoute
  '/administration/roles': typeof DashboardAdministrationRolesRoute
  '/administration/users': typeof DashboardAdministrationUsersRoute
  '/administration': typeof DashboardAdministrationIndexRoute
  '/projects/$projectId/environments/$environmentId/containers': typeof DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersRouteWithChildren
  '/projects/$projectId/environments/$environmentId/containers/$containerId/inspect': typeof DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdInspectRoute
  '/projects/$projectId/environments/$environmentId/containers/$containerId/logs': typeof DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdLogsRoute
  '/projects/$projectId/environments/$environmentId/containers/$containerId': typeof DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_dashboard/administration': typeof DashboardAdministrationRouteWithChildren
  '/_dashboard/forbidden': typeof DashboardForbiddenRoute
  '/_dashboard/infrastructure': typeof DashboardInfrastructureRoute
  '/_dashboard/projects': typeof DashboardProjectsRouteWithChildren
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/administration/audit-logs': typeof DashboardAdministrationAuditLogsRoute
  '/_dashboard/administration/roles': typeof DashboardAdministrationRolesRoute
  '/_dashboard/administration/users': typeof DashboardAdministrationUsersRoute
  '/_dashboard/administration/': typeof DashboardAdministrationIndexRoute
  '/_dashboard/projects/$projectId/environments/$environmentId/containers': typeof DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersRouteWithChildren
  '/_dashboard/projects/$projectId/environments/$environmentId/containers/$containerId': typeof DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdRouteWithChildren
  '/_dashboard/projects/$projectId/environments/$environmentId/containers/$containerId/inspect': typeof DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdInspectRoute
  '/_dashboard/projects/$projectId/environments/$environmentId/containers/$containerId/logs': typeof DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdLogsRoute
  '/_dashboard/projects/$projectId/environments/$environmentId/containers/$containerId/': typeof DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/administration'
    | '/forbidden'
    | '/infrastructure'
    | '/projects'
    | '/administration/audit-logs'
    | '/administration/roles'
    | '/administration/users'
    | '/administration/'
    | '/projects/$projectId/environments/$environmentId/containers'
    | '/projects/$projectId/environments/$environmentId/containers/$containerId'
    | '/projects/$projectId/environments/$environmentId/containers/$containerId/inspect'
    | '/projects/$projectId/environments/$environmentId/containers/$containerId/logs'
    | '/projects/$projectId/environments/$environmentId/containers/$containerId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/forbidden'
    | '/infrastructure'
    | '/projects'
    | '/administration/audit-logs'
    | '/administration/roles'
    | '/administration/users'
    | '/administration'
    | '/projects/$projectId/environments/$environmentId/containers'
    | '/projects/$projectId/environments/$environmentId/containers/$containerId/inspect'
    | '/projects/$projectId/environments/$environmentId/containers/$containerId/logs'
    | '/projects/$projectId/environments/$environmentId/containers/$containerId'
  id:
    | '__root__'
    | '/_auth'
    | '/_dashboard'
    | '/_auth/login'
    | '/_dashboard/administration'
    | '/_dashboard/forbidden'
    | '/_dashboard/infrastructure'
    | '/_dashboard/projects'
    | '/_dashboard/'
    | '/_dashboard/administration/audit-logs'
    | '/_dashboard/administration/roles'
    | '/_dashboard/administration/users'
    | '/_dashboard/administration/'
    | '/_dashboard/projects/$projectId/environments/$environmentId/containers'
    | '/_dashboard/projects/$projectId/environments/$environmentId/containers/$containerId'
    | '/_dashboard/projects/$projectId/environments/$environmentId/containers/$containerId/inspect'
    | '/_dashboard/projects/$projectId/environments/$environmentId/containers/$containerId/logs'
    | '/_dashboard/projects/$projectId/environments/$environmentId/containers/$containerId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/administration': {
      id: '/_dashboard/administration'
      path: '/administration'
      fullPath: '/administration'
      preLoaderRoute: typeof DashboardAdministrationRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/forbidden': {
      id: '/_dashboard/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof DashboardForbiddenRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/infrastructure': {
      id: '/_dashboard/infrastructure'
      path: '/infrastructure'
      fullPath: '/infrastructure'
      preLoaderRoute: typeof DashboardInfrastructureRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/projects': {
      id: '/_dashboard/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof DashboardProjectsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/administration/': {
      id: '/_dashboard/administration/'
      path: '/'
      fullPath: '/administration/'
      preLoaderRoute: typeof DashboardAdministrationIndexRouteImport
      parentRoute: typeof DashboardAdministrationRoute
    }
    '/_dashboard/administration/audit-logs': {
      id: '/_dashboard/administration/audit-logs'
      path: '/audit-logs'
      fullPath: '/administration/audit-logs'
      preLoaderRoute: typeof DashboardAdministrationAuditLogsRouteImport
      parentRoute: typeof DashboardAdministrationRoute
    }
    '/_dashboard/administration/roles': {
      id: '/_dashboard/administration/roles'
      path: '/roles'
      fullPath: '/administration/roles'
      preLoaderRoute: typeof DashboardAdministrationRolesRouteImport
      parentRoute: typeof DashboardAdministrationRoute
    }
    '/_dashboard/administration/users': {
      id: '/_dashboard/administration/users'
      path: '/users'
      fullPath: '/administration/users'
      preLoaderRoute: typeof DashboardAdministrationUsersRouteImport
      parentRoute: typeof DashboardAdministrationRoute
    }
    '/_dashboard/projects/$projectId/environments/$environmentId/containers': {
      id: '/_dashboard/projects/$projectId/environments/$environmentId/containers'
      path: '/$projectId/environments/$environmentId/containers'
      fullPath: '/projects/$projectId/environments/$environmentId/containers'
      preLoaderRoute: typeof DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersRouteImport
      parentRoute: typeof DashboardProjectsRoute
    }
    '/_dashboard/projects/$projectId/environments/$environmentId/containers/$containerId': {
      id: '/_dashboard/projects/$projectId/environments/$environmentId/containers/$containerId'
      path: '/$containerId'
      fullPath: '/projects/$projectId/environments/$environmentId/containers/$containerId'
      preLoaderRoute: typeof DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdRouteImport
      parentRoute: typeof DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersRoute
    }
    '/_dashboard/projects/$projectId/environments/$environmentId/containers/$containerId/': {
      id: '/_dashboard/projects/$projectId/environments/$environmentId/containers/$containerId/'
      path: '/'
      fullPath: '/projects/$projectId/environments/$environmentId/containers/$containerId/'
      preLoaderRoute: typeof DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdIndexRouteImport
      parentRoute: typeof DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdRoute
    }
    '/_dashboard/projects/$projectId/environments/$environmentId/containers/$containerId/inspect': {
      id: '/_dashboard/projects/$projectId/environments/$environmentId/containers/$containerId/inspect'
      path: '/inspect'
      fullPath: '/projects/$projectId/environments/$environmentId/containers/$containerId/inspect'
      preLoaderRoute: typeof DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdInspectRouteImport
      parentRoute: typeof DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdRoute
    }
    '/_dashboard/projects/$projectId/environments/$environmentId/containers/$containerId/logs': {
      id: '/_dashboard/projects/$projectId/environments/$environmentId/containers/$containerId/logs'
      path: '/logs'
      fullPath: '/projects/$projectId/environments/$environmentId/containers/$containerId/logs'
      preLoaderRoute: typeof DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdLogsRouteImport
      parentRoute: typeof DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardAdministrationRouteChildren {
  DashboardAdministrationAuditLogsRoute: typeof DashboardAdministrationAuditLogsRoute
  DashboardAdministrationRolesRoute: typeof DashboardAdministrationRolesRoute
  DashboardAdministrationUsersRoute: typeof DashboardAdministrationUsersRoute
  DashboardAdministrationIndexRoute: typeof DashboardAdministrationIndexRoute
}

const DashboardAdministrationRouteChildren: DashboardAdministrationRouteChildren =
  {
    DashboardAdministrationAuditLogsRoute:
      DashboardAdministrationAuditLogsRoute,
    DashboardAdministrationRolesRoute: DashboardAdministrationRolesRoute,
    DashboardAdministrationUsersRoute: DashboardAdministrationUsersRoute,
    DashboardAdministrationIndexRoute: DashboardAdministrationIndexRoute,
  }

const DashboardAdministrationRouteWithChildren =
  DashboardAdministrationRoute._addFileChildren(
    DashboardAdministrationRouteChildren,
  )

interface DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdRouteChildren {
  DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdInspectRoute: typeof DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdInspectRoute
  DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdLogsRoute: typeof DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdLogsRoute
  DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdIndexRoute: typeof DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdIndexRoute
}

const DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdRouteChildren: DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdRouteChildren =
  {
    DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdInspectRoute:
      DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdInspectRoute,
    DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdLogsRoute:
      DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdLogsRoute,
    DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdIndexRoute:
      DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdIndexRoute,
  }

const DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdRouteWithChildren =
  DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdRoute._addFileChildren(
    DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdRouteChildren,
  )

interface DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersRouteChildren {
  DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdRoute: typeof DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdRouteWithChildren
}

const DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersRouteChildren: DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersRouteChildren =
  {
    DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdRoute:
      DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdRouteWithChildren,
  }

const DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersRouteWithChildren =
  DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersRoute._addFileChildren(
    DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersRouteChildren,
  )

interface DashboardProjectsRouteChildren {
  DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersRoute: typeof DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersRouteWithChildren
}

const DashboardProjectsRouteChildren: DashboardProjectsRouteChildren = {
  DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersRoute:
    DashboardProjectsProjectIdEnvironmentsEnvironmentIdContainersRouteWithChildren,
}

const DashboardProjectsRouteWithChildren =
  DashboardProjectsRoute._addFileChildren(DashboardProjectsRouteChildren)

interface DashboardRouteChildren {
  DashboardAdministrationRoute: typeof DashboardAdministrationRouteWithChildren
  DashboardForbiddenRoute: typeof DashboardForbiddenRoute
  DashboardInfrastructureRoute: typeof DashboardInfrastructureRoute
  DashboardProjectsRoute: typeof DashboardProjectsRouteWithChildren
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdministrationRoute: DashboardAdministrationRouteWithChildren,
  DashboardForbiddenRoute: DashboardForbiddenRoute,
  DashboardInfrastructureRoute: DashboardInfrastructureRoute,
  DashboardProjectsRoute: DashboardProjectsRouteWithChildren,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
