/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as DashboardRouteImport } from './routes/_dashboard'
import { Route as AuthLoginRouteImport } from './routes/_auth.login'
import { Route as DashboardIndexRouteImport } from './routes/_dashboard.index'
import { Route as DashboardAdministrationRouteImport } from './routes/_dashboard.administration'
import { Route as DashboardConfigurationRouteImport } from './routes/_dashboard.configuration'
import { Route as DashboardContainersRouteImport } from './routes/_dashboard.containers'
import { Route as DashboardForbiddenRouteImport } from './routes/_dashboard.forbidden'
import { Route as DashboardInfrastructureRouteImport } from './routes/_dashboard.infrastructure'
import { Route as DashboardProjectsRouteImport } from './routes/_dashboard.projects'
import { Route as DashboardStacksRouteImport } from './routes/_dashboard.stacks'
import { Route as DashboardAdministrationIndexRouteImport } from './routes/_dashboard.administration.index'
import { Route as DashboardAdministrationAuditLogsRouteImport } from './routes/_dashboard.administration.audit-logs'
import { Route as DashboardAdministrationRolesRouteImport } from './routes/_dashboard.administration.roles'
import { Route as DashboardAdministrationUsersRouteImport } from './routes/_dashboard.administration.users'
import { Route as DashboardConfigurationIndexRouteImport } from './routes/_dashboard.configuration.index'
import { Route as DashboardConfigurationInfrastructureRouteImport } from './routes/_dashboard.configuration.infrastructure'
import { Route as DashboardConfigurationProjectsRouteImport } from './routes/_dashboard.configuration.projects'
import { Route as DashboardContainersContainerIdRouteImport } from './routes/_dashboard.containers.$containerId'
import { Route as DashboardContainersContainerIdLogsRouteImport } from './routes/_dashboard.containers.$containerId.logs'
import { Route as DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersRouteImport } from './routes/_dashboard.configuration.projects.$projectId.environments.$environmentId.containers'
import { Route as DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdRouteImport } from './routes/_dashboard.configuration.projects.$projectId.environments.$environmentId.containers.$containerId'
import { Route as DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdIndexRouteImport } from './routes/_dashboard.configuration.projects.$projectId.environments.$environmentId.containers.$containerId.index'
import { Route as DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdInspectRouteImport } from './routes/_dashboard.configuration.projects.$projectId.environments.$environmentId.containers.$containerId.inspect'
import { Route as DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdLogsRouteImport } from './routes/_dashboard.configuration.projects.$projectId.environments.$environmentId.containers.$containerId.logs'

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/_dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdministrationRoute = DashboardAdministrationRouteImport.update({
  id: '/administration',
  path: '/administration',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardConfigurationRoute = DashboardConfigurationRouteImport.update({
  id: '/configuration',
  path: '/configuration',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardContainersRoute = DashboardContainersRouteImport.update({
  id: '/containers',
  path: '/containers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardForbiddenRoute = DashboardForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInfrastructureRoute = DashboardInfrastructureRouteImport.update({
  id: '/infrastructure',
  path: '/infrastructure',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProjectsRoute = DashboardProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStacksRoute = DashboardStacksRouteImport.update({
  id: '/stacks',
  path: '/stacks',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdministrationIndexRoute =
  DashboardAdministrationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardAdministrationRoute,
  } as any)
const DashboardAdministrationAuditLogsRoute =
  DashboardAdministrationAuditLogsRouteImport.update({
    id: '/audit-logs',
    path: '/audit-logs',
    getParentRoute: () => DashboardAdministrationRoute,
  } as any)
const DashboardAdministrationRolesRoute =
  DashboardAdministrationRolesRouteImport.update({
    id: '/roles',
    path: '/roles',
    getParentRoute: () => DashboardAdministrationRoute,
  } as any)
const DashboardAdministrationUsersRoute =
  DashboardAdministrationUsersRouteImport.update({
    id: '/users',
    path: '/users',
    getParentRoute: () => DashboardAdministrationRoute,
  } as any)
const DashboardConfigurationIndexRoute =
  DashboardConfigurationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DashboardConfigurationRoute,
  } as any)
const DashboardConfigurationInfrastructureRoute =
  DashboardConfigurationInfrastructureRouteImport.update({
    id: '/infrastructure',
    path: '/infrastructure',
    getParentRoute: () => DashboardConfigurationRoute,
  } as any)
const DashboardConfigurationProjectsRoute =
  DashboardConfigurationProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => DashboardConfigurationRoute,
  } as any)
const DashboardContainersContainerIdRoute =
  DashboardContainersContainerIdRouteImport.update({
    id: '/$containerId',
    path: '/$containerId',
    getParentRoute: () => DashboardContainersRoute,
  } as any)
const DashboardContainersContainerIdLogsRoute =
  DashboardContainersContainerIdLogsRouteImport.update({
    id: '/logs',
    path: '/logs',
    getParentRoute: () => DashboardContainersContainerIdRoute,
  } as any)
const DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersRoute =
  DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersRouteImport.update(
    {
      id: '/$projectId/environments/$environmentId/containers',
      path: '/$projectId/environments/$environmentId/containers',
      getParentRoute: () => DashboardConfigurationProjectsRoute,
    } as any,
  )
const DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdRoute =
  DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdRouteImport.update(
    {
      id: '/$containerId',
      path: '/$containerId',
      getParentRoute: () =>
        DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersRoute,
    } as any,
  )
const DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdIndexRoute =
  DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdIndexRouteImport.update(
    {
      id: '/',
      path: '/',
      getParentRoute: () =>
        DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdRoute,
    } as any,
  )
const DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdInspectRoute =
  DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdInspectRouteImport.update(
    {
      id: '/inspect',
      path: '/inspect',
      getParentRoute: () =>
        DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdRoute,
    } as any,
  )
const DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdLogsRoute =
  DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdLogsRouteImport.update(
    {
      id: '/logs',
      path: '/logs',
      getParentRoute: () =>
        DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof DashboardIndexRoute
  '/login': typeof AuthLoginRoute
  '/administration': typeof DashboardAdministrationRouteWithChildren
  '/configuration': typeof DashboardConfigurationRouteWithChildren
  '/containers': typeof DashboardContainersRouteWithChildren
  '/forbidden': typeof DashboardForbiddenRoute
  '/infrastructure': typeof DashboardInfrastructureRoute
  '/projects': typeof DashboardProjectsRoute
  '/stacks': typeof DashboardStacksRoute
  '/administration/audit-logs': typeof DashboardAdministrationAuditLogsRoute
  '/administration/roles': typeof DashboardAdministrationRolesRoute
  '/administration/users': typeof DashboardAdministrationUsersRoute
  '/configuration/infrastructure': typeof DashboardConfigurationInfrastructureRoute
  '/configuration/projects': typeof DashboardConfigurationProjectsRouteWithChildren
  '/containers/$containerId': typeof DashboardContainersContainerIdRouteWithChildren
  '/administration/': typeof DashboardAdministrationIndexRoute
  '/configuration/': typeof DashboardConfigurationIndexRoute
  '/containers/$containerId/logs': typeof DashboardContainersContainerIdLogsRoute
  '/configuration/projects/$projectId/environments/$environmentId/containers': typeof DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersRouteWithChildren
  '/configuration/projects/$projectId/environments/$environmentId/containers/$containerId': typeof DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdRouteWithChildren
  '/configuration/projects/$projectId/environments/$environmentId/containers/$containerId/inspect': typeof DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdInspectRoute
  '/configuration/projects/$projectId/environments/$environmentId/containers/$containerId/logs': typeof DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdLogsRoute
  '/configuration/projects/$projectId/environments/$environmentId/containers/$containerId/': typeof DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof DashboardIndexRoute
  '/login': typeof AuthLoginRoute
  '/containers': typeof DashboardContainersRouteWithChildren
  '/forbidden': typeof DashboardForbiddenRoute
  '/infrastructure': typeof DashboardInfrastructureRoute
  '/projects': typeof DashboardProjectsRoute
  '/stacks': typeof DashboardStacksRoute
  '/administration/audit-logs': typeof DashboardAdministrationAuditLogsRoute
  '/administration/roles': typeof DashboardAdministrationRolesRoute
  '/administration/users': typeof DashboardAdministrationUsersRoute
  '/configuration/infrastructure': typeof DashboardConfigurationInfrastructureRoute
  '/configuration/projects': typeof DashboardConfigurationProjectsRouteWithChildren
  '/containers/$containerId': typeof DashboardContainersContainerIdRouteWithChildren
  '/administration': typeof DashboardAdministrationIndexRoute
  '/configuration': typeof DashboardConfigurationIndexRoute
  '/containers/$containerId/logs': typeof DashboardContainersContainerIdLogsRoute
  '/configuration/projects/$projectId/environments/$environmentId/containers': typeof DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersRouteWithChildren
  '/configuration/projects/$projectId/environments/$environmentId/containers/$containerId/inspect': typeof DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdInspectRoute
  '/configuration/projects/$projectId/environments/$environmentId/containers/$containerId/logs': typeof DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdLogsRoute
  '/configuration/projects/$projectId/environments/$environmentId/containers/$containerId': typeof DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_dashboard': typeof DashboardRouteWithChildren
  '/_auth/login': typeof AuthLoginRoute
  '/_dashboard/administration': typeof DashboardAdministrationRouteWithChildren
  '/_dashboard/configuration': typeof DashboardConfigurationRouteWithChildren
  '/_dashboard/containers': typeof DashboardContainersRouteWithChildren
  '/_dashboard/forbidden': typeof DashboardForbiddenRoute
  '/_dashboard/infrastructure': typeof DashboardInfrastructureRoute
  '/_dashboard/projects': typeof DashboardProjectsRoute
  '/_dashboard/stacks': typeof DashboardStacksRoute
  '/_dashboard/': typeof DashboardIndexRoute
  '/_dashboard/administration/audit-logs': typeof DashboardAdministrationAuditLogsRoute
  '/_dashboard/administration/roles': typeof DashboardAdministrationRolesRoute
  '/_dashboard/administration/users': typeof DashboardAdministrationUsersRoute
  '/_dashboard/configuration/infrastructure': typeof DashboardConfigurationInfrastructureRoute
  '/_dashboard/configuration/projects': typeof DashboardConfigurationProjectsRouteWithChildren
  '/_dashboard/containers/$containerId': typeof DashboardContainersContainerIdRouteWithChildren
  '/_dashboard/administration/': typeof DashboardAdministrationIndexRoute
  '/_dashboard/configuration/': typeof DashboardConfigurationIndexRoute
  '/_dashboard/containers/$containerId/logs': typeof DashboardContainersContainerIdLogsRoute
  '/_dashboard/configuration/projects/$projectId/environments/$environmentId/containers': typeof DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersRouteWithChildren
  '/_dashboard/configuration/projects/$projectId/environments/$environmentId/containers/$containerId': typeof DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdRouteWithChildren
  '/_dashboard/configuration/projects/$projectId/environments/$environmentId/containers/$containerId/inspect': typeof DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdInspectRoute
  '/_dashboard/configuration/projects/$projectId/environments/$environmentId/containers/$containerId/logs': typeof DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdLogsRoute
  '/_dashboard/configuration/projects/$projectId/environments/$environmentId/containers/$containerId/': typeof DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/administration'
    | '/configuration'
    | '/containers'
    | '/forbidden'
    | '/infrastructure'
    | '/projects'
    | '/stacks'
    | '/administration/audit-logs'
    | '/administration/roles'
    | '/administration/users'
    | '/configuration/infrastructure'
    | '/configuration/projects'
    | '/containers/$containerId'
    | '/administration/'
    | '/configuration/'
    | '/containers/$containerId/logs'
    | '/configuration/projects/$projectId/environments/$environmentId/containers'
    | '/configuration/projects/$projectId/environments/$environmentId/containers/$containerId'
    | '/configuration/projects/$projectId/environments/$environmentId/containers/$containerId/inspect'
    | '/configuration/projects/$projectId/environments/$environmentId/containers/$containerId/logs'
    | '/configuration/projects/$projectId/environments/$environmentId/containers/$containerId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/containers'
    | '/forbidden'
    | '/infrastructure'
    | '/projects'
    | '/stacks'
    | '/administration/audit-logs'
    | '/administration/roles'
    | '/administration/users'
    | '/configuration/infrastructure'
    | '/configuration/projects'
    | '/containers/$containerId'
    | '/administration'
    | '/configuration'
    | '/containers/$containerId/logs'
    | '/configuration/projects/$projectId/environments/$environmentId/containers'
    | '/configuration/projects/$projectId/environments/$environmentId/containers/$containerId/inspect'
    | '/configuration/projects/$projectId/environments/$environmentId/containers/$containerId/logs'
    | '/configuration/projects/$projectId/environments/$environmentId/containers/$containerId'
  id:
    | '__root__'
    | '/_auth'
    | '/_dashboard'
    | '/_auth/login'
    | '/_dashboard/administration'
    | '/_dashboard/configuration'
    | '/_dashboard/containers'
    | '/_dashboard/forbidden'
    | '/_dashboard/infrastructure'
    | '/_dashboard/projects'
    | '/_dashboard/stacks'
    | '/_dashboard/'
    | '/_dashboard/administration/audit-logs'
    | '/_dashboard/administration/roles'
    | '/_dashboard/administration/users'
    | '/_dashboard/configuration/infrastructure'
    | '/_dashboard/configuration/projects'
    | '/_dashboard/containers/$containerId'
    | '/_dashboard/administration/'
    | '/_dashboard/configuration/'
    | '/_dashboard/containers/$containerId/logs'
    | '/_dashboard/configuration/projects/$projectId/environments/$environmentId/containers'
    | '/_dashboard/configuration/projects/$projectId/environments/$environmentId/containers/$containerId'
    | '/_dashboard/configuration/projects/$projectId/environments/$environmentId/containers/$containerId/inspect'
    | '/_dashboard/configuration/projects/$projectId/environments/$environmentId/containers/$containerId/logs'
    | '/_dashboard/configuration/projects/$projectId/environments/$environmentId/containers/$containerId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dashboard': {
      id: '/_dashboard'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_dashboard/': {
      id: '/_dashboard/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/administration': {
      id: '/_dashboard/administration'
      path: '/administration'
      fullPath: '/administration'
      preLoaderRoute: typeof DashboardAdministrationRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/configuration': {
      id: '/_dashboard/configuration'
      path: '/configuration'
      fullPath: '/configuration'
      preLoaderRoute: typeof DashboardConfigurationRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/containers': {
      id: '/_dashboard/containers'
      path: '/containers'
      fullPath: '/containers'
      preLoaderRoute: typeof DashboardContainersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/forbidden': {
      id: '/_dashboard/forbidden'
      path: '/forbidden'
      fullPath: '/forbidden'
      preLoaderRoute: typeof DashboardForbiddenRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/infrastructure': {
      id: '/_dashboard/infrastructure'
      path: '/infrastructure'
      fullPath: '/infrastructure'
      preLoaderRoute: typeof DashboardInfrastructureRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/projects': {
      id: '/_dashboard/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof DashboardProjectsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/stacks': {
      id: '/_dashboard/stacks'
      path: '/stacks'
      fullPath: '/stacks'
      preLoaderRoute: typeof DashboardStacksRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_dashboard/administration/': {
      id: '/_dashboard/administration/'
      path: '/'
      fullPath: '/administration/'
      preLoaderRoute: typeof DashboardAdministrationIndexRouteImport
      parentRoute: typeof DashboardAdministrationRoute
    }
    '/_dashboard/administration/audit-logs': {
      id: '/_dashboard/administration/audit-logs'
      path: '/audit-logs'
      fullPath: '/administration/audit-logs'
      preLoaderRoute: typeof DashboardAdministrationAuditLogsRouteImport
      parentRoute: typeof DashboardAdministrationRoute
    }
    '/_dashboard/administration/roles': {
      id: '/_dashboard/administration/roles'
      path: '/roles'
      fullPath: '/administration/roles'
      preLoaderRoute: typeof DashboardAdministrationRolesRouteImport
      parentRoute: typeof DashboardAdministrationRoute
    }
    '/_dashboard/administration/users': {
      id: '/_dashboard/administration/users'
      path: '/users'
      fullPath: '/administration/users'
      preLoaderRoute: typeof DashboardAdministrationUsersRouteImport
      parentRoute: typeof DashboardAdministrationRoute
    }
    '/_dashboard/configuration/': {
      id: '/_dashboard/configuration/'
      path: '/'
      fullPath: '/configuration/'
      preLoaderRoute: typeof DashboardConfigurationIndexRouteImport
      parentRoute: typeof DashboardConfigurationRoute
    }
    '/_dashboard/configuration/infrastructure': {
      id: '/_dashboard/configuration/infrastructure'
      path: '/infrastructure'
      fullPath: '/configuration/infrastructure'
      preLoaderRoute: typeof DashboardConfigurationInfrastructureRouteImport
      parentRoute: typeof DashboardConfigurationRoute
    }
    '/_dashboard/configuration/projects': {
      id: '/_dashboard/configuration/projects'
      path: '/projects'
      fullPath: '/configuration/projects'
      preLoaderRoute: typeof DashboardConfigurationProjectsRouteImport
      parentRoute: typeof DashboardConfigurationRoute
    }
    '/_dashboard/containers/$containerId': {
      id: '/_dashboard/containers/$containerId'
      path: '/$containerId'
      fullPath: '/containers/$containerId'
      preLoaderRoute: typeof DashboardContainersContainerIdRouteImport
      parentRoute: typeof DashboardContainersRoute
    }
    '/_dashboard/containers/$containerId/logs': {
      id: '/_dashboard/containers/$containerId/logs'
      path: '/logs'
      fullPath: '/containers/$containerId/logs'
      preLoaderRoute: typeof DashboardContainersContainerIdLogsRouteImport
      parentRoute: typeof DashboardContainersContainerIdRoute
    }
    '/_dashboard/configuration/projects/$projectId/environments/$environmentId/containers': {
      id: '/_dashboard/configuration/projects/$projectId/environments/$environmentId/containers'
      path: '/$projectId/environments/$environmentId/containers'
      fullPath: '/configuration/projects/$projectId/environments/$environmentId/containers'
      preLoaderRoute: typeof DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersRouteImport
      parentRoute: typeof DashboardConfigurationProjectsRoute
    }
    '/_dashboard/configuration/projects/$projectId/environments/$environmentId/containers/$containerId': {
      id: '/_dashboard/configuration/projects/$projectId/environments/$environmentId/containers/$containerId'
      path: '/$containerId'
      fullPath: '/configuration/projects/$projectId/environments/$environmentId/containers/$containerId'
      preLoaderRoute: typeof DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdRouteImport
      parentRoute: typeof DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersRoute
    }
    '/_dashboard/configuration/projects/$projectId/environments/$environmentId/containers/$containerId/': {
      id: '/_dashboard/configuration/projects/$projectId/environments/$environmentId/containers/$containerId/'
      path: '/'
      fullPath: '/configuration/projects/$projectId/environments/$environmentId/containers/$containerId/'
      preLoaderRoute: typeof DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdIndexRouteImport
      parentRoute: typeof DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdRoute
    }
    '/_dashboard/configuration/projects/$projectId/environments/$environmentId/containers/$containerId/inspect': {
      id: '/_dashboard/configuration/projects/$projectId/environments/$environmentId/containers/$containerId/inspect'
      path: '/inspect'
      fullPath: '/configuration/projects/$projectId/environments/$environmentId/containers/$containerId/inspect'
      preLoaderRoute: typeof DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdInspectRouteImport
      parentRoute: typeof DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdRoute
    }
    '/_dashboard/configuration/projects/$projectId/environments/$environmentId/containers/$containerId/logs': {
      id: '/_dashboard/configuration/projects/$projectId/environments/$environmentId/containers/$containerId/logs'
      path: '/logs'
      fullPath: '/configuration/projects/$projectId/environments/$environmentId/containers/$containerId/logs'
      preLoaderRoute: typeof DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdLogsRouteImport
      parentRoute: typeof DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface DashboardAdministrationRouteChildren {
  DashboardAdministrationAuditLogsRoute: typeof DashboardAdministrationAuditLogsRoute
  DashboardAdministrationRolesRoute: typeof DashboardAdministrationRolesRoute
  DashboardAdministrationUsersRoute: typeof DashboardAdministrationUsersRoute
  DashboardAdministrationIndexRoute: typeof DashboardAdministrationIndexRoute
}

const DashboardAdministrationRouteChildren: DashboardAdministrationRouteChildren =
  {
    DashboardAdministrationAuditLogsRoute:
      DashboardAdministrationAuditLogsRoute,
    DashboardAdministrationRolesRoute: DashboardAdministrationRolesRoute,
    DashboardAdministrationUsersRoute: DashboardAdministrationUsersRoute,
    DashboardAdministrationIndexRoute: DashboardAdministrationIndexRoute,
  }

const DashboardAdministrationRouteWithChildren =
  DashboardAdministrationRoute._addFileChildren(
    DashboardAdministrationRouteChildren,
  )

interface DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdRouteChildren {
  DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdInspectRoute: typeof DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdInspectRoute
  DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdLogsRoute: typeof DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdLogsRoute
  DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdIndexRoute: typeof DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdIndexRoute
}

const DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdRouteChildren: DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdRouteChildren =
  {
    DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdInspectRoute:
      DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdInspectRoute,
    DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdLogsRoute:
      DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdLogsRoute,
    DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdIndexRoute:
      DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdIndexRoute,
  }

const DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdRouteWithChildren =
  DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdRoute._addFileChildren(
    DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdRouteChildren,
  )

interface DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersRouteChildren {
  DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdRoute: typeof DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdRouteWithChildren
}

const DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersRouteChildren: DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersRouteChildren =
  {
    DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdRoute:
      DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersContainerIdRouteWithChildren,
  }

const DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersRouteWithChildren =
  DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersRoute._addFileChildren(
    DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersRouteChildren,
  )

interface DashboardConfigurationProjectsRouteChildren {
  DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersRoute: typeof DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersRouteWithChildren
}

const DashboardConfigurationProjectsRouteChildren: DashboardConfigurationProjectsRouteChildren =
  {
    DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersRoute:
      DashboardConfigurationProjectsProjectIdEnvironmentsEnvironmentIdContainersRouteWithChildren,
  }

const DashboardConfigurationProjectsRouteWithChildren =
  DashboardConfigurationProjectsRoute._addFileChildren(
    DashboardConfigurationProjectsRouteChildren,
  )

interface DashboardConfigurationRouteChildren {
  DashboardConfigurationInfrastructureRoute: typeof DashboardConfigurationInfrastructureRoute
  DashboardConfigurationProjectsRoute: typeof DashboardConfigurationProjectsRouteWithChildren
  DashboardConfigurationIndexRoute: typeof DashboardConfigurationIndexRoute
}

const DashboardConfigurationRouteChildren: DashboardConfigurationRouteChildren =
  {
    DashboardConfigurationInfrastructureRoute:
      DashboardConfigurationInfrastructureRoute,
    DashboardConfigurationProjectsRoute:
      DashboardConfigurationProjectsRouteWithChildren,
    DashboardConfigurationIndexRoute: DashboardConfigurationIndexRoute,
  }

const DashboardConfigurationRouteWithChildren =
  DashboardConfigurationRoute._addFileChildren(
    DashboardConfigurationRouteChildren,
  )

interface DashboardContainersContainerIdRouteChildren {
  DashboardContainersContainerIdLogsRoute: typeof DashboardContainersContainerIdLogsRoute
}

const DashboardContainersContainerIdRouteChildren: DashboardContainersContainerIdRouteChildren =
  {
    DashboardContainersContainerIdLogsRoute:
      DashboardContainersContainerIdLogsRoute,
  }

const DashboardContainersContainerIdRouteWithChildren =
  DashboardContainersContainerIdRoute._addFileChildren(
    DashboardContainersContainerIdRouteChildren,
  )

interface DashboardContainersRouteChildren {
  DashboardContainersContainerIdRoute: typeof DashboardContainersContainerIdRouteWithChildren
}

const DashboardContainersRouteChildren: DashboardContainersRouteChildren = {
  DashboardContainersContainerIdRoute:
    DashboardContainersContainerIdRouteWithChildren,
}

const DashboardContainersRouteWithChildren =
  DashboardContainersRoute._addFileChildren(DashboardContainersRouteChildren)

interface DashboardRouteChildren {
  DashboardAdministrationRoute: typeof DashboardAdministrationRouteWithChildren
  DashboardConfigurationRoute: typeof DashboardConfigurationRouteWithChildren
  DashboardContainersRoute: typeof DashboardContainersRouteWithChildren
  DashboardForbiddenRoute: typeof DashboardForbiddenRoute
  DashboardInfrastructureRoute: typeof DashboardInfrastructureRoute
  DashboardProjectsRoute: typeof DashboardProjectsRoute
  DashboardStacksRoute: typeof DashboardStacksRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdministrationRoute: DashboardAdministrationRouteWithChildren,
  DashboardConfigurationRoute: DashboardConfigurationRouteWithChildren,
  DashboardContainersRoute: DashboardContainersRouteWithChildren,
  DashboardForbiddenRoute: DashboardForbiddenRoute,
  DashboardInfrastructureRoute: DashboardInfrastructureRoute,
  DashboardProjectsRoute: DashboardProjectsRoute,
  DashboardStacksRoute: DashboardStacksRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
